apiVersion: v1
kind: Service
metadata:
  name: weatherservice
  labels:
    app: weatherservice
spec:
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: weatherservice-port
  selector:
    app: weatherservice
  type: ClusterIP