apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherservice
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: weatherservice
  replicas: 1
  template:
    metadata:
      labels:
        app: weatherservice
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 3000
        fsGroup: 2000
      restartPolicy: Always
      containers:
        - name: weatherservice
          image: {{ .Values.weatherservice.image.name }}:{{ .Values.weatherservice.image.version }}
          securityContext:
            allowPrivilegeEscalation: false
          env:
            # Environment variables for configuring gRPC listening
            - name: QUARKUS_GRPC_SERVER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: QUARKUS_GRPC_SERVER_PORT
              value: "9090"
          ports:
            - containerPort: 9090